version: '3.8'

services:
  nats:
    image: nats-streaming:latest
    command: -cid cluster1 -m 8222 --cluster_name test-cluster
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: